#ifndef BORON_INCLUDE_BORON_GLOBAL_HPP_
#define BORON_INCLUDE_BORON_GLOBAL_HPP_

#define BORON_VERSION_MAJOR 0
#define BORON_VERSION_MINOR 1
#define BORON_VERSION_PATCH 0
#define BORON_VERSION_STRING "0.1.0"

#define BORON_NODISCARD [[nodiscard]]

#define BORON_EXPORT

#endif